### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ronaldkunenborg** [olihawkins/d3-hexjson#2]
Hi Oli, I was about to write my own d3-plugin for hex boards because I was busy working on a game as Firebase demonstration. And I needed a hexmap. However, when I re-checked the D3 repository to make sure I hadn't overlooked anything, I just saw your plugin pop up, doing at least part of what I wanted to do. And referring to my source as well (redblobgames.com) so I was pretty happy not to have to do everything. 

However, I probably need the whole redblobgames toolbox. Are you going to do everything on the site, or just stop here? Because in that case I'm going to write "d3-hexmap", use your plugin as requirement, and build from there. 

Please let me know your intentions! You can reach me at "ronaldkunenborg (at) grundsatzlich-it.nl". And if you like, you can check out my website at https://www.grundsatzlich-it.nl . I'd really like to hear from you.

In the mean time I'm going to write the plugin code, but I'll hold off on publishing.

**Comment by olihawkins** [comment]
Hi Ronald. Thanks for getting in touch. I think you should probably go ahead and build a more fully featured plugin for hexmaps using d3-hexjson as a requirement. I wrote d3-hexjson to provide the core functionality of rendering HexJSON data, and while there are one or two additional features I may add over time, I don't intend for it to provide a complete solution for creating every kind of hexmap. I think it would be great if such a library existed, but I only have limited time for software development so I have to be quite targeted in what I do. Please do let me know about anything you create though as I would be very interested in it. Sorry I can't offer more support and I hope that helps you decide what to do.

**Comment by ronaldkunenborg** [comment]
Hi Oli, that’s fine. I’ll do that. Best regards, Ronald.

**Comment by ronaldkunenborg** [comment]
Hi Oli,

I’ve posted a pull request (first one ever *cheers* ) for an extension of the HexJSON standard. It basically boils down to the following:

- Version number of HexJSON version in the HexJSON.
- Extra attribute maxCoordinates that indicate the direction of the positive sides of the x- and y-axis. Should be “minCoordinates” in order to match the origin. 
- Extra values for layout: axial-r and axial-q. 

The above should cover all possible ways to denote the layout of a hexmap. Once everyone agrees to the above, I’ll update d3-hexjson and post a pull request for that too, if you like.

By the way: do you have any idea when someone will respond to pull requests etc. on the hexmap project? Or are those folks completely different ones?

With best regards,
Ronald Kunenborg.

**Comment by olihawkins** [comment]
Hi Ronald,

That sounds good. I don't know the HexJSON authors personally, but your suggestions sound sensible to me. I am very happy for you to submit a PR for d3-hexjson when the HexJSON spec is updated. Could I ask you to add tests to cover any new features, make sure that the current tests still pass, and update the readme with descriptions of any new features? None of this sounds like it would break backwards compatibility though, which is good.

Cheers,

Oli

**Comment by ronaldkunenborg** [comment]
Hi Oli,

Great! I’ll start working on it then. After I update my first Pull request 

Yes, I did my best to avoid breaking backwards compatibility, which would be a pain. 
I’ll do as you suggest wrt to tests and readme. Good points.

You will see the pull request in a week or so, I hope.

Best regards,
Ronald.
